repos:
  # General housekeeping
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  # Linting, formatting, and import sorting (ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check
        args: [--fix, --ignore=F811]
      - id: ruff-format
  # Security: Common security issues (bandit)
  # things such as hardcoded pws, SQL injection risks, unsafe use of `exec`, etc.
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        # -lll = high Severity, low confidence (less noise)
        # -r = recursive
        args: ["-lll", "-ii", "-r"]
        # exclude checks for test files usually makes sense
        exclude: ^tests/

  # Security: Detect hardcoded secrets (gitleaks)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
